server:
  port: ${SPRING_SERVER_PORT:8080}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:mopp-service}
  datasource:      #로컬 db 연결 설정
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:            #jpa 설정
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
        default_batch_fetch_size: ${SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_BATCH_FETCH_SIZE} #최적화 옵션

    show_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: ${GOOGLE_REDIRECT_URI}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_SERVER_PORT:6379}

jwt:
  secret: ${JWT_SECRET}
  access-token-expirations: ${JWT_ACCESS_TOKEN_EXPIRATIONS}
  refresh-token-expirations: ${JWT_REFRESH_TOKEN_EXPIRATIONS}

app:
  frontend-url: ${REDIRECT_URL}